"""empty message

Revision ID: 228b585dd975
Revises: 
Create Date: 2020-11-23 20:56:26.328182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228b585dd975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_created'), 'post', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_created'), table_name='post')
    # ### end Alembic commands ###
