"""empty message

Revision ID: 310925810764
Revises: 228b585dd975
Create Date: 2020-11-25 13:01:49.110879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310925810764'
down_revision = '228b585dd975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pre_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pre_body')
    # ### end Alembic commands ###
