"""empty message

Revision ID: 4fca6309f014
Revises: 310925810764
Create Date: 2020-11-27 22:09:38.779193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fca6309f014'
down_revision = '310925810764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'count')
    # ### end Alembic commands ###
