"""empty message

Revision ID: 5b5c3e1a383a
Revises: e0d96b1ee623
Create Date: 2020-11-30 09:32:51.946912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5c3e1a383a'
down_revision = 'e0d96b1ee623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storageimg', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'storageimg', type_='foreignkey')
    op.create_foreign_key(None, 'storageimg', 'user', ['user_id'], ['id'])
    op.drop_column('storageimg', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storageimg', sa.Column('post_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'storageimg', type_='foreignkey')
    op.create_foreign_key(None, 'storageimg', 'post', ['post_id'], ['id'])
    op.drop_column('storageimg', 'user_id')
    # ### end Alembic commands ###
